# This file has been generated by node2nix 1.7.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:

let
  sources = {
    "@goto-bus-stop/common-shake-2.3.0" = {
      name = "_at_goto-bus-stop_slash_common-shake";
      packageName = "@goto-bus-stop/common-shake";
      version = "2.3.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/@goto-bus-stop/common-shake/-/common-shake-2.3.0.tgz";
        sha512 =
          "c1kyQGNRNbklB+Gm9oZtuIdNkVJLYSU32S4IXe5LgJJwyeyBQoATZb5y0HwjMx9v9tBe9G02DZfTj4NkOllNJA==";
      };
    };
    "JSONStream-1.3.5" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz";
        sha512 =
          "E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ==";
      };
    };
    "acorn-4.0.13" = {
      name = "acorn";
      packageName = "acorn";
      version = "4.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-4.0.13.tgz";
        sha1 = "105495ae5361d697bd195c825192e1ad7f253787";
      };
    };
    "acorn-5.7.3" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.7.3.tgz";
        sha512 =
          "T/zvzYRfbVojPWahDsE5evJdHb3oJoQfFbsrKM7w5Zcs++Tr257tia3BmMP8XYVjp1S9RZXQMh7gao96BlqZOw==";
      };
    };
    "acorn-6.2.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-6.2.1.tgz";
        sha512 =
          "JD0xT5FCRDNyjDda3Lrg/IxFscp9q4tiYtxE1/nOzlKCk7hIRuYjhq1kCNkbPjMRMZuFq20HNQn1I9k8Oj0E+Q==";
      };
    };
    "acorn-dynamic-import-4.0.0" = {
      name = "acorn-dynamic-import";
      packageName = "acorn-dynamic-import";
      version = "4.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/acorn-dynamic-import/-/acorn-dynamic-import-4.0.0.tgz";
        sha512 =
          "d3OEjQV4ROpoflsnUA8HozoIR504TFxNivYEUi6uwz0IYhBkTDXGuWlNdMtybRt3nqVx/L6XqMt0FxkXuWKZhw==";
      };
    };
    "acorn-node-1.7.0" = {
      name = "acorn-node";
      packageName = "acorn-node";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-node/-/acorn-node-1.7.0.tgz";
        sha512 =
          "XhahLSsCB6X6CJbe+uNu3Mn9sJBNFxtBN9NLgAOQovfS6Kh0lDUtmlclhjn9CvEK7A7YyRU13PXlNcpSiLI9Yw==";
      };
    };
    "acorn-walk-6.2.0" = {
      name = "acorn-walk";
      packageName = "acorn-walk";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-6.2.0.tgz";
        sha512 =
          "7evsyfH1cLOCdAzZAd43Cic04yKydNx0cF+7tiA19p1XnLLPU4dpCQOqpjqwokFe//vS0QqfqqjCS2JkiIs0cA==";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "array-from-2.1.1" = {
      name = "array-from";
      packageName = "array-from";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-from/-/array-from-2.1.1.tgz";
        sha1 = "cfe9d8c26628b9dc5aecc62a9f5d8f1f352c1195";
      };
    };
    "asn1.js-4.10.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.10.1.tgz";
        sha512 =
          "p32cOF5q0Zqs9uBiONKYLm6BClCoBCM5O9JfeUSlnQLBTxYdTK+pW+nXflm8UkKd2UYlEbYz5qEi0JuZR9ckSw==";
      };
    };
    "assert-1.5.0" = {
      name = "assert";
      packageName = "assert";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.5.0.tgz";
        sha512 =
          "EDsgawzwoun2CZkCgtxJbv392v4nbk9XDD06zI+kQYoBM/3RBWLlEyJARDOmhAAosBjWACEkKL6S+lIZtcAubA==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 =
          "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bn.js-4.11.8" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.8.tgz";
        sha512 =
          "ItfYfPLkWHUjckQCk8xC+LwxgK8NYcXywGigJgSwOP8Y2iyWT4f2vsZnoOXTTbo+o5yXmIUJ4gn5538SO5S3gA==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 =
          "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "browser-pack-5.0.1" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "5.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browser-pack/-/browser-pack-5.0.1.tgz";
        sha1 = "4197719b20c6e0aaa09451c5111e53efb6fbc18d";
      };
    };
    "browser-pack-6.1.0" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "6.1.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browser-pack/-/browser-pack-6.1.0.tgz";
        sha512 =
          "erYug8XoqzU3IfcU8fUgyHqyOXqIE4tUTTQ+7mqUjQlvnXkOO6OlT9c/ZoJVHYoAaqGxr09CN53G7XIsO4KtWA==";
      };
    };
    "browser-pack-flat-3.4.2" = {
      name = "browser-pack-flat";
      packageName = "browser-pack-flat";
      version = "3.4.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browser-pack-flat/-/browser-pack-flat-3.4.2.tgz";
        sha512 =
          "TrUo6n2fGSOCYFAKkt/EkgenytAuuCI88fmXFA60aNFVHvz3CZEBTXYSvvXVpU6xpjM8lj/6vkC6Exn8KPjtPw==";
      };
    };
    "browser-process-hrtime-0.1.3" = {
      name = "browser-process-hrtime";
      packageName = "browser-process-hrtime";
      version = "0.1.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browser-process-hrtime/-/browser-process-hrtime-0.1.3.tgz";
        sha512 =
          "bRFnI4NnjO6cnyLmOV/7PVoDEMJChlcfN0z4s1YMBY989/SvlfMI1lgCnkFUs53e9gQF+w7qu7XdllSTiSl8Aw==";
      };
    };
    "browser-resolve-1.11.3" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.3.tgz";
        sha512 =
          "exDi1BYWB/6raKHmDTCicQfTkqwN5fioMFV4j8BsfMU4R2DK/QfZfK7kOVkmWCNANf0snkBzqGqAJBao9gZMdQ==";
      };
    };
    "browser-unpack-1.4.2" = {
      name = "browser-unpack";
      packageName = "browser-unpack";
      version = "1.4.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browser-unpack/-/browser-unpack-1.4.2.tgz";
        sha512 =
          "uHkiY4bmXjjBBWoKH1aRnEGTQxUUCCcVtoJfH9w1lmGGjETY4u93Zk+GRYkCE/SRMrdoMTINQ/1/manr/3aMVA==";
      };
    };
    "browserify-16.5.0" = {
      name = "browserify";
      packageName = "browserify";
      version = "16.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-16.5.0.tgz";
        sha512 =
          "6bfI3cl76YLAnCZ75AGu/XPOsqUhRyc0F/olGIJeCxtfxF2HvPKEcmjU9M8oAPxl4uBY1U7Nry33Q6koV3f2iw==";
      };
    };
    "browserify-aes-1.2.0" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.2.0.tgz";
        sha512 =
          "+7CHXqGuspUn/Sl5aO7Ea0xWGAtETPXNSAjHo48JfLdPWcMng33Xe4znFvQweqc/uzk5zSOI3H52CYnjCfb5hA==";
      };
    };
    "browserify-cipher-1.0.1" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.1.tgz";
        sha512 =
          "sPhkz0ARKbf4rRQt2hTpAHqn47X3llLkUGn+xEJzLjwY8LRs2p0v7ljvI5EyoRO/mexrNunNECisZs+gw2zz1w==";
      };
    };
    "browserify-des-1.0.2" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.2.tgz";
        sha512 =
          "BioO1xf3hFwz4kc6iBhI3ieDFompMhrMlnDFC4/0/vd5MokpuAc3R+LYbwTA9A5Yc9pq9UYPqffKpW2ObuwX5A==";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "browserify-sign-4.0.4" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.0.4";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.0.4.tgz";
        sha1 = "aa4eb68e5d7b658baa6bf6a57e630cbd7a93d298";
      };
    };
    "browserify-zlib-0.2.0" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.2.0.tgz";
        sha512 =
          "Z942RysHXmJrhqk88FmKBVq/v5tqmSkDz7p54G/MGyjMnCFFnC79XWNbg+Vta8W6Wb2qtSZTSxIGkJrRpCFEiA==";
      };
    };
    "buffer-5.4.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.4.3.tgz";
        sha512 =
          "zvj65TkFeIt3i6aj5bIvJDzjjQQGs4o/sNoezg1F1kYap9Nu2jcUdpwzRSJTHMMzG0H7bZkn4rNQpImhuxWX2A==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 =
          "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "builtin-status-codes-3.0.0" = {
      name = "builtin-status-codes";
      packageName = "builtin-status-codes";
      version = "3.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/builtin-status-codes/-/builtin-status-codes-3.0.0.tgz";
        sha1 = "85982878e21b98e1c66425e03d0174788f569ee8";
      };
    };
    "bundle-collapser-1.3.0" = {
      name = "bundle-collapser";
      packageName = "bundle-collapser";
      version = "1.3.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/bundle-collapser/-/bundle-collapser-1.3.0.tgz";
        sha1 = "f4b4ff58b2f22ee7701b20fa76306e23f53a3fb6";
      };
    };
    "cached-path-relative-1.0.2" = {
      name = "cached-path-relative";
      packageName = "cached-path-relative";
      version = "1.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/cached-path-relative/-/cached-path-relative-1.0.2.tgz";
        sha512 =
          "5r2GqsoEb4qMTTN9J+WzXfjov+hjxT+j3u5K+kIVNIwAd99DLCJE9pBIMP1qVeybV6JiijL385Oz0DcYxfbOIg==";
      };
    };
    "call-matcher-1.1.0" = {
      name = "call-matcher";
      packageName = "call-matcher";
      version = "1.1.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/call-matcher/-/call-matcher-1.1.0.tgz";
        sha512 =
          "IoQLeNwwf9KTNbtSA7aEBb1yfDbdnzwjCetjkC8io5oGeOmK2CBNdg0xr+tadRYKO0p7uQyZzvon0kXlZbvGrw==";
      };
    };
    "camel-case-3.0.0" = {
      name = "camel-case";
      packageName = "camel-case";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camel-case/-/camel-case-3.0.0.tgz";
        sha1 = "ca3c3688a4e9cf3a4cda777dc4dcbc713249cf73";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "choo-7.0.0" = {
      name = "choo";
      packageName = "choo";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/choo/-/choo-7.0.0.tgz";
        sha512 =
          "amHTsaD1QT5rNtuTTEomvp0VRzySVYU3fOttZq0M4mLqK0LGl9ySXXb2iw7JFiziegocq402glzEFkktOl+vyw==";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 =
          "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "combine-source-map-0.6.1" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.6.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.6.1.tgz";
        sha1 = "9b4a09c316033d768e0f11e029fa2730e079ad96";
      };
    };
    "combine-source-map-0.8.0" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.8.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.8.0.tgz";
        sha1 = "a58d0df042c186fcf822a8e8015f5450d2d79a8b";
      };
    };
    "commander-2.20.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.0.tgz";
        sha512 =
          "7j2y+40w61zy6YC2iRNpUe/NwhNyoXrYpHMrSunaMG64nRnaf96zO/KMQR4OyN/UnE5KLyEBnKHd4aG3rskjpQ==";
      };
    };
    "common-shakeify-0.6.2" = {
      name = "common-shakeify";
      packageName = "common-shakeify";
      version = "0.6.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/common-shakeify/-/common-shakeify-0.6.2.tgz";
        sha512 =
          "vxlXr26fqxm8ZJ0jh8MlvpeN6IbyUKqsVmgb4rAjDM/0f4nKebiHaAXpF/Mm86W9ENR5iSI7UOnUTylpVyplUA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 =
          "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "console-browserify-1.2.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/console-browserify/-/console-browserify-1.2.0.tgz";
        sha512 =
          "ZMkYO/LkF17QvCPqM0gxw8yUzigAOZOSWSHg91FH6orS7vcEj5dVZTidN2fQ14yBSdg97RqhSNwLUXInd52OTA==";
      };
    };
    "constants-browserify-1.0.0" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/constants-browserify/-/constants-browserify-1.0.0.tgz";
        sha1 = "c20b96d8c617748aaf1c16021760cd27fcb8cb75";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "convert-source-map-1.6.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.6.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.6.0.tgz";
        sha512 =
          "eFu7XigvxdZ1ETfbgPBohgyQ/Z++C0eEhTor0qRwBw9unw+L0/6V8wkSuGgzdThkiS5lSpdptOQPD8Ak40a+7A==";
      };
    };
    "core-js-2.6.9" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.6.9.tgz";
        sha512 =
          "HOpZf6eXmnl7la+cUdMnLvUxKNqLUzJvgIziQ0DiF3JwSImNphIqdGqzj6hIKyX04MmV0poclQ7+wjWvxQyR2A==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "count-lines-0.1.2" = {
      name = "count-lines";
      packageName = "count-lines";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/count-lines/-/count-lines-0.1.2.tgz";
        sha1 = "e33493fb6860a82f7159d8237843fbfaefee5962";
      };
    };
    "create-ecdh-4.0.3" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.3.tgz";
        sha512 =
          "GbEHQPMOswGpKXM9kCWVrremUcBmjteUaQ01T9rkKCPDXfUHX0IoP9LpHYo2NPFampa4e+/pFDc3jQdxrxQLaw==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 =
          "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 =
          "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "crypto-browserify-3.12.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.12.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.12.0.tgz";
        sha512 =
          "fz4spIh+znjO2VjL+IdhEpRJ3YN6sMzITSBijk6FK2UvTqruSQW+/cCZTSNsMiZNvUeq0CqurF+dAbyiGOY6Wg==";
      };
    };
    "d-1.0.1" = {
      name = "d";
      packageName = "d";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-1.0.1.tgz";
        sha512 =
          "m62ShEObQ39CfralilEQRjH6oAMtNCV1xJyEx5LpRYUVN+EviphDgUc/F3hnYbADmkiNs67Y+3ylmlG7Lnu+FA==";
      };
    };
    "dash-ast-1.0.0" = {
      name = "dash-ast";
      packageName = "dash-ast";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dash-ast/-/dash-ast-1.0.0.tgz";
        sha512 =
          "Vy4dx7gquTeMcQR/hDkYLGUnwVil6vk4FOOct+djUnHOUWt+zJPJAaRIXaAFkPXtJjvlY7o3rfRu0/3hpnwoUA==";
      };
    };
    "debug-3.2.6" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.6.tgz";
        sha512 =
          "mel+jf7nrtEl5Pn1Qx46zARXKDpBbvzezse7p7LqINmdoIk8PYP5SySaxEmYv6TZ0JyEKA1hsCId6DIhgITtWQ==";
      };
    };
    "dedent-0.7.0" = {
      name = "dedent";
      packageName = "dedent";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dedent/-/dedent-0.7.0.tgz";
        sha1 = "2495ddbaf6eb874abb0e1be9df22d2e5a544326c";
      };
    };
    "deep-equal-1.0.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
        sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "deps-sort-2.0.1" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-2.0.1.tgz";
        sha512 =
          "1orqXQr5po+3KI6kQb9A4jnXT1PBwggGl2d7Sq2xsnOeI9GPcE/tGcF9UiSZtZBM7MukY4cAh7MemS6tZYipfw==";
      };
    };
    "des.js-1.0.1" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.1.tgz";
        sha512 =
          "Q0I4pfFrv2VPd34/vfLrFOoRmlYj3OV50i7fskps1jZWK1kApMWWT9G6RRUeYedLcBDIhnSDaUvJMb3AhUlaEA==";
      };
    };
    "detective-5.2.0" = {
      name = "detective";
      packageName = "detective";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-5.2.0.tgz";
        sha512 =
          "6SsIx+nUUbuK0EthKjv0zrdnajCCXVYGmbYYiYjFVpzcjwEs/JMDZ8tPRG29J/HhN56t3GJp2cGSWDRjjot8Pg==";
      };
    };
    "diffie-hellman-5.0.3" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.3.tgz";
        sha512 =
          "kqag/Nl+f3GwyK25fhUMYj81BUOrZ9IuJsjIcDE5icNM9FJHAVm3VcUDxdLPoQtTuUylWm6ZIknYJwwaPxsUzg==";
      };
    };
    "document-ready-2.0.2" = {
      name = "document-ready";
      packageName = "document-ready";
      version = "2.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/document-ready/-/document-ready-2.0.2.tgz";
        sha512 =
          "C0ht1cPSVzL5ALWnLiXDGfQXbzmNMJrLQ7wzc2fwz5x/wlZun+uzTGJGdKgfygZQ9i7RNRxI+OV909zXKFPycA==";
      };
    };
    "dom-walk-0.1.1" = {
      name = "dom-walk";
      packageName = "dom-walk";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-walk/-/dom-walk-0.1.1.tgz";
        sha1 = "672226dc74c8f799ad35307df936aba11acd6018";
      };
    };
    "domain-browser-1.2.0" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/domain-browser/-/domain-browser-1.2.0.tgz";
        sha512 =
          "jnjyiM6eRyZl2H+W8Q/zLMA481hzi0eszAaBUzIVnmYVDBbnLxVNnfu1HgEBvCbL+71FrxMl3E6lpKH7Ge3OXA==";
      };
    };
    "duplexer-0.1.1" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer/-/duplexer-0.1.1.tgz";
        sha1 = "ace6ff808c1ce66b57d1ebf97977acb02334cfc1";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "duplexify-3.7.1" = {
      name = "duplexify";
      packageName = "duplexify";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexify/-/duplexify-3.7.1.tgz";
        sha512 =
          "07z8uv2wMyS51kKhD1KsdXJg5WQ6t93RneqRxUHnskXVtlYYkLqM0gqStQZ3pj073g687jPCHrqNfCzawLYh5g==";
      };
    };
    "elliptic-6.5.2" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.5.2.tgz";
        sha512 =
          "f4x70okzZbIQl/NSRLkI/+tteV/9WqL98zx+SQ69KbXxmVrmjwsNUPn/gYJJ0sHvEak24cZgHIPegRePAtA/xw==";
      };
    };
    "end-of-stream-1.4.1" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.1.tgz";
        sha512 =
          "1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==";
      };
    };
    "envify-4.1.0" = {
      name = "envify";
      packageName = "envify";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/envify/-/envify-4.1.0.tgz";
        sha512 =
          "IKRVVoAYr4pIx4yIWNsz9mOsboxlNXiu7TNBnem/K/uTHdkyzXWDzHCK7UTolqBbgaBz0tQHsD3YNls0uIIjiw==";
      };
    };
    "es5-ext-0.10.50" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.50";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.50.tgz";
        sha512 =
          "KMzZTPBkeQV/JcSQhI5/z6d9VWJ3EnQ194USTUwIYZ2ZbpN8+SGXQKt1h68EX44+qt+Fzr8DO17vnxrw7c3agw==";
      };
    };
    "es6-iterator-2.0.3" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.3.tgz";
        sha1 = "a7de889141a05a94b0854403b2d0a0fbfa98f3b7";
      };
    };
    "es6-map-0.1.5" = {
      name = "es6-map";
      packageName = "es6-map";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-map/-/es6-map-0.1.5.tgz";
        sha1 = "9136e0503dcc06a301690f0bb14ff4e364e949f0";
      };
    };
    "es6-set-0.1.5" = {
      name = "es6-set";
      packageName = "es6-set";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-set/-/es6-set-0.1.5.tgz";
        sha1 = "d2b3ec5d4d800ced818db538d28974db0a73ccb1";
      };
    };
    "es6-symbol-3.1.1" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.1.tgz";
        sha1 = "bf00ef4fdab6ba1b46ecb7b629b4c7ed5715cc77";
      };
    };
    "es6-weak-map-2.0.3" = {
      name = "es6-weak-map";
      packageName = "es6-weak-map";
      version = "2.0.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/es6-weak-map/-/es6-weak-map-2.0.3.tgz";
        sha512 =
          "p5um32HOTO1kP+w7PRnB+5lQ43Z6muuMuIMffvDN8ZB4GcnjLBV6zGStpbASIMk4DCAvEaamhe2zhyCb/QXXsA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "escodegen-1.11.1" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.11.1.tgz";
        sha512 =
          "JwiqFD9KdGVVpeuRa68yU3zZnBEOcPs0nKW7wZzXky8Z7tffdYUHbe11bPCV5jYlK6DVdKLWLm0f5I/QlL0Kmw==";
      };
    };
    "escope-3.6.0" = {
      name = "escope";
      packageName = "escope";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escope/-/escope-3.6.0.tgz";
        sha1 = "e01975e812781a163a6dadfdd80398dc64c889c3";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 =
          "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "espurify-1.8.1" = {
      name = "espurify";
      packageName = "espurify";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/espurify/-/espurify-1.8.1.tgz";
        sha512 =
          "ZDko6eY/o+D/gHCWyHTU85mKDgYcS4FJj7S+YD6WIInm7GQ6AnOjmcL4+buFV/JOztVLELi/7MmuGU5NHta0Mg==";
      };
    };
    "esrecurse-4.2.1" = {
      name = "esrecurse";
      packageName = "esrecurse";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrecurse/-/esrecurse-4.2.1.tgz";
        sha512 =
          "64RBB++fIOAXPw3P9cy89qfMlvZEXZkqqJkjqqXIvzP5ezRZjW+lPWjw35UX/3EhUPFYbg5ER4JYgDw4007/DQ==";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "estree-is-function-1.0.0" = {
      name = "estree-is-function";
      packageName = "estree-is-function";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/estree-is-function/-/estree-is-function-1.0.0.tgz";
        sha512 =
          "nSCWn1jkSq2QAtkaVLJZY2ezwcFO161HVc174zL1KPW3RJ+O6C3eJb8Nx7OXzvhoEv+nLgSR1g71oWUHUDTrJA==";
      };
    };
    "estree-is-identifier-1.0.0" = {
      name = "estree-is-identifier";
      packageName = "estree-is-identifier";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/estree-is-identifier/-/estree-is-identifier-1.0.0.tgz";
        sha512 =
          "2BDRGrkQJV/NhCAmmE33A35WAaxq3WQaGHgQuD//7orGWfpFqj8Srkwvx0TH+20yIdOF1yMQwi8anv5ISec2AQ==";
      };
    };
    "estree-is-member-expression-1.0.0" = {
      name = "estree-is-member-expression";
      packageName = "estree-is-member-expression";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/estree-is-member-expression/-/estree-is-member-expression-1.0.0.tgz";
        sha512 =
          "Ec+X44CapIGExvSZN+pGkmr5p7HwUVQoPQSd458Lqwvaf4/61k/invHSh4BYK8OXnCkfEhWuIoG5hayKLQStIg==";
      };
    };
    "estree-is-require-1.0.0" = {
      name = "estree-is-require";
      packageName = "estree-is-require";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/estree-is-require/-/estree-is-require-1.0.0.tgz";
        sha512 =
          "oWxQdSEmnUwNZsDQYiBNpVxKEhMmsJQSSxnDrwsr1MWtooCLfhgzsNGzmokdmfK0EzEIS5V4LPvqxv1Kmb1vvA==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 =
          "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "event-emitter-0.3.5" = {
      name = "event-emitter";
      packageName = "event-emitter";
      version = "0.3.5";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/event-emitter/-/event-emitter-0.3.5.tgz";
        sha1 = "df8c69eef1647923c7157b9ce83840610b02cc39";
      };
    };
    "events-2.1.0" = {
      name = "events";
      packageName = "events";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-2.1.0.tgz";
        sha512 =
          "3Zmiobend8P9DjmKAty0Era4jV8oJ0yGYe2nJJAxgymF9+N8F2m0hhZiMoWtcfepExzNKZumFU3ksdQbInGWCg==";
      };
    };
    "evp_bytestokey-1.0.3" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.3.tgz";
        sha512 =
          "/f2Go4TognH/KvCISP7OUsHn85hT9nUkxxA9BEWxFn+Oj9o8ZNLm/40hdlgSLyuOimsrTKLUMEorQexp/aPQeA==";
      };
    };
    "extend-1.3.0" = {
      name = "extend";
      packageName = "extend";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-1.3.0.tgz";
        sha1 = "d1516fb0ff5624d2ebf9123ea1dac5a1994004f8";
      };
    };
    "falafel-2.1.0" = {
      name = "falafel";
      packageName = "falafel";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/falafel/-/falafel-2.1.0.tgz";
        sha1 = "96bb17761daba94f46d001738b3cedf3a67fe06c";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "fast-safe-stringify-2.0.7" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.7";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.7.tgz";
        sha512 =
          "Utm6CdzT+6xsDk2m8S6uL8VHxNwI6Jub+e9NYTcAms28T84pTa25GJQV9j0CY0N1rM8hK4x6grpF2BQf+2qwVA==";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "from2-2.3.0" = {
      name = "from2";
      packageName = "from2";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/from2/-/from2-2.3.0.tgz";
        sha1 = "8bfb5502bde4a4d36cfdeea007fcca21d7e382af";
      };
    };
    "from2-string-1.1.0" = {
      name = "from2-string";
      packageName = "from2-string";
      version = "1.1.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/from2-string/-/from2-string-1.1.0.tgz";
        sha1 = "18282b27d08a267cb3030cd2b8b4b0f212af752a";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 =
          "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-assigned-identifiers-1.2.0" = {
      name = "get-assigned-identifiers";
      packageName = "get-assigned-identifiers";
      version = "1.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/get-assigned-identifiers/-/get-assigned-identifiers-1.2.0.tgz";
        sha512 =
          "mBBwmeGTrxEMO4pMaaf/uUEFHnYtwr8FTe8Y/mer4rcV/bye0qGm6pw1bGZFGStxC5O76c5ZAVBGnqHmOaJpdQ==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 =
          "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "global-4.4.0" = {
      name = "global";
      packageName = "global";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/global/-/global-4.4.0.tgz";
        sha512 =
          "wv/LAoHdRE3BeTGz53FAamhGlPLhlssK45usmGFThIi4XqnBmjKQ16u+RNbP7WvigRZDxUsM0J3gcQ5yicaL0w==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 =
          "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "hash-base-3.0.4" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.0.4.tgz";
        sha1 = "5fc8686847ecd73499403319a6b0a3f3f6ae4918";
      };
    };
    "hash.js-1.1.7" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.7.tgz";
        sha512 =
          "taOaskGt4z4SOANNseOviYDvjEJinIkRgmp7LbKP2YTTmVxWBl87s/uzK9r+44BclBSp2X7K1hqeNfz9JbBeXA==";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "https-browserify-1.0.0" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/https-browserify/-/https-browserify-1.0.0.tgz";
        sha1 = "ec06c10e0a34c0f2faf199f7fd7fc78fffd03c73";
      };
    };
    "hyperscript-attribute-to-property-1.0.2" = {
      name = "hyperscript-attribute-to-property";
      packageName = "hyperscript-attribute-to-property";
      version = "1.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/hyperscript-attribute-to-property/-/hyperscript-attribute-to-property-1.0.2.tgz";
        sha512 =
          "oerMul16jZCmrbNsUw8QgrtDzF8lKgFri1bKQjReLw1IhiiNkI59CWuzZjJDGT79UQ1YiWqXhJMv/tRMVqgtkA==";
      };
    };
    "hyperx-2.5.4" = {
      name = "hyperx";
      packageName = "hyperx";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyperx/-/hyperx-2.5.4.tgz";
        sha512 =
          "iOkSh7Yse7lsN/B9y7OsevLWjeXPqGuHQ5SbwaiJM5xAhWFqhoN6erpK1dQsS12OFU36lyai1pnx1mmzWLQqcA==";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 =
          "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 =
          "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inline-source-map-0.5.0" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.5.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.5.0.tgz";
        sha1 = "4a4c5dd8e4fb5e9b3cda60c822dfadcaee66e0af";
      };
    };
    "inline-source-map-0.6.2" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.6.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.6.2.tgz";
        sha1 = "f9393471c18a79d1724f863fa38b586370ade2a5";
      };
    };
    "insert-module-globals-7.2.0" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "7.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-7.2.0.tgz";
        sha512 =
          "VE6NlW+WGn2/AeOMd496AHFYmE7eLKkUY6Ty31k4og5vmA3Fjuwe9v6ifH6Xx/Hz27QvdoMoviw1/pqWRB09Sw==";
      };
    };
    "is-boolean-attribute-0.0.1" = {
      name = "is-boolean-attribute";
      packageName = "is-boolean-attribute";
      version = "0.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/is-boolean-attribute/-/is-boolean-attribute-0.0.1.tgz";
        sha1 = "24ab59b7dcb9da3612c773e60c656565e5a0980c";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 =
          "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-buffer-2.0.3" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.3.tgz";
        sha512 =
          "U15Q7MXTuZlrbymiz95PJpZxu8IlipAp4dtS3wOdgPXx3mqBnslrWU14kxfHB+Py/+2PVKSr37dMAgM2A4uArw==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "labeled-stream-splicer-2.0.2" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "2.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-2.0.2.tgz";
        sha512 =
          "Ca4LSXFFZUjPScRaqOcFxneA0VpKZr4MMYCljyQr4LIewTLb3Y0IUTIsnBBsVubIeEfxeSZpSjSsRM8APEQaAw==";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "lower-case-1.1.4" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-1.1.4.tgz";
        sha1 = "9a2cabd1b9e8e0ae993a4bf7d5875c39c42e8eac";
      };
    };
    "magic-string-0.23.2" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.23.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/magic-string/-/magic-string-0.23.2.tgz";
        sha512 =
          "oIUZaAxbcxYIp4AyLafV6OVKoB3YouZs0UTCJ8mOKBHNyJgGDaMJ4TgA+VylJh6fx7EQCC52XkbURxxG9IoJXA==";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 =
          "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "merge-source-map-1.0.4" = {
      name = "merge-source-map";
      packageName = "merge-source-map";
      version = "1.0.4";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/merge-source-map/-/merge-source-map-1.0.4.tgz";
        sha1 = "a5de46538dae84d4114cc5ea02b4772a6346701f";
      };
    };
    "miller-rabin-4.0.1" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.1.tgz";
        sha512 =
          "115fLhvZVqWwHPbClyntxEVfVDfl9DLLTuJvq3g2O/Oxi8AiNouAHvDSzHS0viUJc+V5vm3eq91Xwqn9dp4jRA==";
      };
    };
    "min-document-2.19.0" = {
      name = "min-document";
      packageName = "min-document";
      version = "2.19.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/min-document/-/min-document-2.19.0.tgz";
        sha1 = "7bd282e3f5842ed295bb748cdd9f1ffa2c824685";
      };
    };
    "minify-stream-1.2.0" = {
      name = "minify-stream";
      packageName = "minify-stream";
      version = "1.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/minify-stream/-/minify-stream-1.2.0.tgz";
        sha512 =
          "bIjBH7uGROwzWwgtbLO7U/yi+NBTLGs5YYidUiGD9nJZ5wuxX0485c48vtJ7WlNZNnKvHXA1D1ZXpfWJqf4fyg==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 =
          "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 =
          "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "module-deps-6.2.2" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-6.2.2.tgz";
        sha512 =
          "a9y6yDv5u5I4A+IPHTnqFxcaKr4p50/zxTjcQJaX2ws9tN/W6J6YXnEKhqRyPhl494dkcxx951onSKVezmI+3w==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 =
          "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "multi-stage-sourcemap-0.2.1" = {
      name = "multi-stage-sourcemap";
      packageName = "multi-stage-sourcemap";
      version = "0.2.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/multi-stage-sourcemap/-/multi-stage-sourcemap-0.2.1.tgz";
        sha1 = "b09fc8586eaa17f81d575c4ad02e0f7a3f6b1105";
      };
    };
    "mutexify-1.2.0" = {
      name = "mutexify";
      packageName = "mutexify";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mutexify/-/mutexify-1.2.0.tgz";
        sha512 =
          "oprzxd2zhfrJqEuB98qc1dRMMonClBQ57UPDjnbcrah4orEMTq1jq3+AcdFe5ePzdbJXI7zmdhfftIdMnhYFoQ==";
      };
    };
    "nanoassert-1.1.0" = {
      name = "nanoassert";
      packageName = "nanoassert";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoassert/-/nanoassert-1.1.0.tgz";
        sha1 = "4f3152e09540fde28c76f44b19bbcd1d5a42478d";
      };
    };
    "nanobench-2.1.1" = {
      name = "nanobench";
      packageName = "nanobench";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanobench/-/nanobench-2.1.1.tgz";
        sha512 =
          "z+Vv7zElcjN+OpzAxAquUayFLGK3JI/ubCl0Oh64YQqsTGG09CGqieJVQw4ui8huDnnAgrvTv93qi5UaOoNj8A==";
      };
    };
    "nanobus-4.4.0" = {
      name = "nanobus";
      packageName = "nanobus";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanobus/-/nanobus-4.4.0.tgz";
        sha512 =
          "Hv9USGyH8EsPy0o8pPWE7x3YRIfuZDgMBirzjU6XLebhiSK2g53JlfqgolD0c39ne6wXAfaBNcIAvYe22Bav+Q==";
      };
    };
    "nanocomponent-6.5.2" = {
      name = "nanocomponent";
      packageName = "nanocomponent";
      version = "6.5.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/nanocomponent/-/nanocomponent-6.5.2.tgz";
        sha512 =
          "k/C/Taxno+imoQL6/8tlbMuwvXq4fwjKHphBuZ8Sh/8NiaCBixMWitRZ3uW0Pyz1mrPOHhs6evkKngR1Y8Vi2g==";
      };
    };
    "nanohref-3.1.0" = {
      name = "nanohref";
      packageName = "nanohref";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanohref/-/nanohref-3.1.0.tgz";
        sha512 =
          "2DyDzc8B/29xRCDprTt8UscdsF3E/axcHQMIBFR+WM1cj1ku7hqxQWwMYDOajfEuv5fZdVTh+NBuFronappMQQ==";
      };
    };
    "nanohtml-1.6.3" = {
      name = "nanohtml";
      packageName = "nanohtml";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanohtml/-/nanohtml-1.6.3.tgz";
        sha512 =
          "yf44+EN5e+nPiZdb9SjP5ugrO3HqTHJMWucfA57tbzmsiV3M7tBFxjEicaV+TuQY3xSlqpsgG/THM2jZLXRByw==";
      };
    };
    "nanolru-1.0.0" = {
      name = "nanolru";
      packageName = "nanolru";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanolru/-/nanolru-1.0.0.tgz";
        sha512 =
          "GyQkE8M32pULhQk7Sko5raoIbPalAk90ICG+An4fq6fCsFHsP6fB2K46WGXVdoJpy4SGMnZ/EKbo123fZJomWg==";
      };
    };
    "nanomorph-5.4.0" = {
      name = "nanomorph";
      packageName = "nanomorph";
      version = "5.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanomorph/-/nanomorph-5.4.0.tgz";
        sha512 =
          "PJPh+P/NeiKphHNmCO8afkIhRbmeWxwpWhM1imKGWQMyuK1ul4rfnzKqrf3PEhbXYsqhMWCBEMm+q4jddYGODw==";
      };
    };
    "nanoquery-1.3.0" = {
      name = "nanoquery";
      packageName = "nanoquery";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoquery/-/nanoquery-1.3.0.tgz";
        sha512 =
          "eZv8Ct2PZn/CdOmD2BgLNwjhhPmxg4tXhygp0roaRer5RqBFB0gm0wHIb5VZcL0CS0r+yWQ1kBVYG7S1jUyG0A==";
      };
    };
    "nanoraf-3.1.0" = {
      name = "nanoraf";
      packageName = "nanoraf";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoraf/-/nanoraf-3.1.0.tgz";
        sha512 =
          "7Emv5Pv/fvgVK6yrud93WsdO4d3AUqLoP38Cpn0chYe+tT/wu25Yl2guxBjE3ngRrI5Yd9DxaTCgCFi1uq7hgQ==";
      };
    };
    "nanorouter-4.0.0" = {
      name = "nanorouter";
      packageName = "nanorouter";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanorouter/-/nanorouter-4.0.0.tgz";
        sha512 =
          "HQ6VeNpFhIx/vKjqQiVUodeu0SvRb6ekkmkzf4pXMjkAZy0RS2jsIWZmzob9s6ORW0dfhYHpL7+w7T+bE5kNCQ==";
      };
    };
    "nanoscheduler-1.0.3" = {
      name = "nanoscheduler";
      packageName = "nanoscheduler";
      version = "1.0.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/nanoscheduler/-/nanoscheduler-1.0.3.tgz";
        sha512 =
          "jBbrF3qdU9321r8n9X7yu18DjP31Do2ItJm3mWrt90wJTrnDO+HXpoV7ftaUglAtjgj9s+OaCxGufbvx6pvbEQ==";
      };
    };
    "nanotiming-7.3.1" = {
      name = "nanotiming";
      packageName = "nanotiming";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanotiming/-/nanotiming-7.3.1.tgz";
        sha512 =
          "l3lC7v/PfOuRWQa8vV29Jo6TG10wHtnthLElFXs4Te4Aas57Fo4n1Q8LH9n+NDh9riOzTVvb2QNBhTS4JUKNjw==";
      };
    };
    "next-tick-1.0.0" = {
      name = "next-tick";
      packageName = "next-tick";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-tick/-/next-tick-1.0.0.tgz";
        sha1 = "ca86d1fe8828169b0120208e3dc8424b9db8342c";
      };
    };
    "no-case-2.3.2" = {
      name = "no-case";
      packageName = "no-case";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-2.3.2.tgz";
        sha512 =
          "rmTZ9kz+f3rCvK2TD1Ue/oZlns7OGoIWP4fc3llxxRXlOkHKoWPPWJOfFYpITabSow43QJbRIoHQXtt10VldyQ==";
      };
    };
    "normalize-html-whitespace-0.2.0" = {
      name = "normalize-html-whitespace";
      packageName = "normalize-html-whitespace";
      version = "0.2.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/normalize-html-whitespace/-/normalize-html-whitespace-0.2.0.tgz";
        sha1 = "101722f6423551c75cdb8f9d104ff850daf1e10e";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 =
          "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "on-load-3.4.1" = {
      name = "on-load";
      packageName = "on-load";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-load/-/on-load-3.4.1.tgz";
        sha512 =
          "Q3v6aurn5Pif4Rk1QZhnH/azZiKZqiroCcRkPlEccwTl4UFomAGFAqZz8XRCGN/KtuX4DwXCn9SB/edSSoV+Hg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "os-browserify-0.3.0" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.3.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/os-browserify/-/os-browserify-0.3.0.tgz";
        sha1 = "854373c7f5c2315914fc9bfc6bd8238fdda1ec27";
      };
    };
    "pako-1.0.11" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.11.tgz";
        sha512 =
          "4hLB8Py4zZce5s4yd9XzopqwVv/yGNhV1Bl8NTmCq1763HeK2+EwVTv+leGeL13Dnh2wfbqowVPXCIO0z4taYw==";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "parse-asn1-5.1.5" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.1.5.tgz";
        sha512 =
          "jkMYn1dcJqF6d5CpU689bq7w/b5ALS9ROVSpQDPrZsqqesUJii9qutvoT5ltGedNXMO2e16YUWIghG9KxaViTQ==";
      };
    };
    "path-browserify-0.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.1.tgz";
        sha512 =
          "BapA40NHICOS+USX9SN4tyhq+A2RrN/Ws5F0Z5aMHDp98Fl86lX8Oti8B7uN93L4Ifv4fHOEA+pQw87gmMO/lQ==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 =
          "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "pbkdf2-3.0.17" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.17.tgz";
        sha512 =
          "U/il5MsrZp7mGg3mSQfn742na2T+1/vHDCG5/iTI3X9MKUuYUZVLQhyRsg06mCgDBTd57TxzgZt7P+fYfjRLtA==";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "pretty-hrtime-1.0.3" = {
      name = "pretty-hrtime";
      packageName = "pretty-hrtime";
      version = "1.0.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/pretty-hrtime/-/pretty-hrtime-1.0.3.tgz";
        sha1 = "b7e3ea42435a4c9b2759d99e0f201eb195802ee1";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 =
          "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "public-encrypt-4.0.3" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.3.tgz";
        sha512 =
          "zVpa8oKZSz5bTMTFClc1fQOnyyEzpl5ozpi1B5YcvBrdohMjH2rfsBtyXcuNuwjsDIXmBYlF2N5FlJYhR29t8Q==";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 =
          "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "randomfill-1.0.4" = {
      name = "randomfill";
      packageName = "randomfill";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomfill/-/randomfill-1.0.4.tgz";
        sha512 =
          "87lcbR8+MhcWcUiQ+9e+Rwx8MyR2P7qnt15ynUlbm3TU/fjbgz4GsvfSUDTemtCCtVCqb4ZcEFlyPNTh9bBTLw==";
      };
    };
    "read-only-stream-2.0.0" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "2.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/read-only-stream/-/read-only-stream-2.0.0.tgz";
        sha1 = "2724fd6a8113d73764ac288d4386270c1dbf17f0";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 =
          "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 =
          "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "remove-array-items-1.1.1" = {
      name = "remove-array-items";
      packageName = "remove-array-items";
      version = "1.1.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/remove-array-items/-/remove-array-items-1.1.1.tgz";
        sha512 =
          "MXW/jtHyl5F1PZI7NbpS8SOtympdLuF20aoWJT5lELR1p/HJDd5nqW8Eu9uLh/hCRY3FgvrIT5AwDCgBODklcA==";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "resolve-1.15.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.15.1.tgz";
        sha512 =
          "84oo6ZTtoTUpjgNEr5SJyzQhzL72gaRodsSfyxC/AXRvwu0Yse9H8eF9IpGo7b8YetZhlI6v7ZQ6bKBFV/6S7w==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 =
          "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 =
          "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "scope-analyzer-2.0.5" = {
      name = "scope-analyzer";
      packageName = "scope-analyzer";
      version = "2.0.5";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/scope-analyzer/-/scope-analyzer-2.0.5.tgz";
        sha512 =
          "+U5H0417mnTEstCD5VwOYO7V4vYuSqwqjFap40ythe67bhMFL5C3UgPwyBv7KDJsqUBIKafOD57xMlh1rN7eaw==";
      };
    };
    "scroll-to-anchor-1.1.0" = {
      name = "scroll-to-anchor";
      packageName = "scroll-to-anchor";
      version = "1.1.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/scroll-to-anchor/-/scroll-to-anchor-1.1.0.tgz";
        sha1 = "c99b8d2e5d95056752787ca78095ab75b520b3fd";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 =
          "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shasum-object-1.0.0" = {
      name = "shasum-object";
      packageName = "shasum-object";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/shasum-object/-/shasum-object-1.0.0.tgz";
        sha512 =
          "Iqo5rp/3xVi6M4YheapzZhhGPVs0yZwHj7wvwQ1B9z8H6zk+FEnI7y3Teq7qwnekfEhu8WmG2z0z4iWZaxLWVg==";
      };
    };
    "shell-quote-1.7.2" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.7.2.tgz";
        sha512 =
          "mRz/m/JVscCrkMyPqHc/bczi3OQHkLTqXHEFu0zDhK/qfv3UcOA4SVmRCLmos4bhjr9ekVQubj/R7waKapmiQg==";
      };
    };
    "simple-concat-1.0.0" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.0.tgz";
        sha1 = "7344cbb8b6e26fb27d66b2fc86f9f6d5997521c6";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha1 = "c24bc146ca517c1471f5dacbe2571b2b7f9e3346";
      };
    };
    "source-map-0.4.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.4.4.tgz";
        sha1 = "eba4f5da9c0dc999de68032d8b4f76173652036b";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 =
          "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.13" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.13";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.13.tgz";
        sha512 =
          "SHSKFHadjVA5oR4PPqhtAVdcBWwRYVd6g6cAXnIbRiIwc2EhPrTuKUBdSLvlEKyIP3GCf89fltvcZiP9MMFA1w==";
      };
    };
    "sourcemap-codec-1.4.6" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.6";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.6.tgz";
        sha512 =
          "1ZooVLYFxC448piVLBbtOxFcXwnymH9oUF8nRd3CuYDVvkRBxRl6pB4Mtas5a4drtL+E8LDgFkQNcgIw6tc8Hg==";
      };
    };
    "stream-browserify-2.0.2" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "2.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.2.tgz";
        sha512 =
          "nX6hmklHs/gr2FuxYDltq8fJA1GDlxKQCz8O/IM4atRqBH8OORmBNgfvW5gG10GT/qQ9u0CzIvr2X5Pkt6ntqg==";
      };
    };
    "stream-combiner-0.2.2" = {
      name = "stream-combiner";
      packageName = "stream-combiner";
      version = "0.2.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/stream-combiner/-/stream-combiner-0.2.2.tgz";
        sha1 = "aec8cbac177b56b6f4fa479ced8c1912cee52858";
      };
    };
    "stream-combiner2-1.1.1" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.1.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.1.1.tgz";
        sha1 = "fb4d8a1420ea362764e21ad4780397bebcb41cbe";
      };
    };
    "stream-http-3.1.0" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-3.1.0.tgz";
        sha512 =
          "cuB6RgO7BqC4FBYzmnvhob5Do3wIdIsXAgGycHJnW+981gHqoYcYz9lqjJrk8WXRddbwPuqPYRl+bag6mYv4lw==";
      };
    };
    "stream-shift-1.0.0" = {
      name = "stream-shift";
      packageName = "stream-shift";
      version = "1.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/stream-shift/-/stream-shift-1.0.0.tgz";
        sha1 = "d5c752825e5367e786f78e18e445ea223a155952";
      };
    };
    "stream-splicer-2.0.1" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "2.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/stream-splicer/-/stream-splicer-2.0.1.tgz";
        sha512 =
          "Xizh4/NPuYSyAXyT7g8IvdJ9HJpxIGL9PjyhtywCZvvP0OPIdqyrr4dMikeuvY8xahpdKEBlBTySe583totajg==";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 =
          "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "syntax-error-1.4.0" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.4.0";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/syntax-error/-/syntax-error-1.4.0.tgz";
        sha512 =
          "YPPlu67mdnHGTup2A8ff7BC2Pjq0e0Yp/IyTFN03zWO0RcK07uLcbi7C2KpGR2FvWbaB0+bfE27a+sBKebSo7w==";
      };
    };
    "terser-3.17.0" = {
      name = "terser";
      packageName = "terser";
      version = "3.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-3.17.0.tgz";
        sha512 =
          "/FQzzPJmCpjAH9Xvk2paiWrFq+5M6aVOf+2KRbwhByISDX/EujxsK+BAvrhb6H+2rtrLCHK9N01wO014vrIwVQ==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "through2-1.1.1" = {
      name = "through2";
      packageName = "through2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-1.1.1.tgz";
        sha1 = "0847cbc4449f3405574dbdccd9bb841b83ac3545";
      };
    };
    "through2-2.0.5" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.5.tgz";
        sha512 =
          "/mrRod8xqpA+IHSLyGCQ2s8SPHiCDEeQJSep1jqLYeEUClOFG2Qsh+4FU6G9VeqpZnGW/Su8LQGc4YKni5rYSQ==";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "tinyify-2.5.1" = {
      name = "tinyify";
      packageName = "tinyify";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinyify/-/tinyify-2.5.1.tgz";
        sha512 =
          "6osa3xxZDjhaGJJem1kTyMuUZxbRuJp6l6DRFUGfqUzg/xxNSRetBPQ84TFaxohJQBEKUi1NFzTfxPKH9VEAmg==";
      };
    };
    "transform-ast-2.4.4" = {
      name = "transform-ast";
      packageName = "transform-ast";
      version = "2.4.4";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/transform-ast/-/transform-ast-2.4.4.tgz";
        sha512 =
          "AxjeZAcIOUO2lev2GDe3/xZ1Q0cVGjIMk5IsriTy8zbWlsEnjeB025AhkhBJHoy997mXpLd4R+kRbvnnQVuQHQ==";
      };
    };
    "tty-browserify-0.0.1" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.1.tgz";
        sha512 =
          "C3TaO7K81YvjCgQH9Q1S3R3P3BtN3RIM8n+OvX4il1K1zgE8ZhI0op7kClgkxtutIE8hQrcrHBXvIheqKUUCxw==";
      };
    };
    "type-1.0.3" = {
      name = "type";
      packageName = "type";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/type/-/type-1.0.3.tgz";
        sha512 =
          "51IMtNfVcee8+9GJvj0spSuFcZHe9vSib6Xtgsny1Km9ugyz2mbS08I3rsUIRYgJohFRFU1160sgRodYz378Hg==";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "uglifyify-5.0.1" = {
      name = "uglifyify";
      packageName = "uglifyify";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglifyify/-/uglifyify-5.0.1.tgz";
        sha512 =
          "PO44rgExvwj3rkK0UzenHVnPU18drBy9x9HOUmgkuRh6K2KIsDqrB5LqxGtjybgGTOS1JeP8SBc+TN5rhiva6w==";
      };
    };
    "umd-3.0.3" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.3.tgz";
        sha512 =
          "4IcGSufhFshvLNcMCV80UnQVlZ5pMOC8mvNPForqwA4+lzYQuetTESLDQkeLmihq8bRcnpbQa48Wb8Lh16/xow==";
      };
    };
    "unassert-1.5.1" = {
      name = "unassert";
      packageName = "unassert";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unassert/-/unassert-1.5.1.tgz";
        sha1 = "cbc88ec387417c5a5e4c02d3cd07be98bd75ff76";
      };
    };
    "unassertify-2.1.1" = {
      name = "unassertify";
      packageName = "unassertify";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unassertify/-/unassertify-2.1.1.tgz";
        sha512 =
          "YIAaIlc6/KC9Oib8cVZLlpDDhK1UTEuaDyx9BwD97xqxDZC0cJOqwFcs/Y6K3m73B5VzHsRTBLXNO0dxS/GkTw==";
      };
    };
    "undeclared-identifiers-1.1.3" = {
      name = "undeclared-identifiers";
      packageName = "undeclared-identifiers";
      version = "1.1.3";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/undeclared-identifiers/-/undeclared-identifiers-1.1.3.tgz";
        sha512 =
          "pJOW4nxjlmfwKApE4zvxLScM/njmwj/DiUBv7EabwE4O8kRUy+HIwxQtZLBPll/jx1LJyBcqNfB3/cpv9EZwOw==";
      };
    };
    "upper-case-1.1.3" = {
      name = "upper-case";
      packageName = "upper-case";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/upper-case/-/upper-case-1.1.3.tgz";
        sha1 = "f6b4501c2ec4cdd26ba78be7222961de77621598";
      };
    };
    "url-0.11.0" = {
      name = "url";
      packageName = "url";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.11.0.tgz";
        sha1 = "3838e97cfc60521eb73c525a8e55bfdd9e2e28f1";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "util-0.10.4" = {
      name = "util";
      packageName = "util";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.4.tgz";
        sha512 =
          "0Pm9hTQ3se5ll1XihRic3FDIku70C+iHUdT/W926rSgHV5QgXsYbKZN8MSC3tJtSkhuROzvsQjAaFENRXr+19A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "vm-browserify-1.1.2" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "1.1.2";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/vm-browserify/-/vm-browserify-1.1.2.tgz";
        sha512 =
          "2ham8XPWTONajOR0ohOKOHXkm3+gaBmGut3SRuu75xLd/RRaY6vqgh8NBYYk7+RW3u5AtzPQZG8F10LHkl0lAQ==";
      };
    };
    "wayfarer-7.0.0" = {
      name = "wayfarer";
      packageName = "wayfarer";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wayfarer/-/wayfarer-7.0.0.tgz";
        sha512 =
          "mKF6pIaNHTdmwWjzrjbIWDnlgFFPC7MuQ+gbUVjBLpXp40mYmiP3Eb7qtO0rgAcsj3kuzGu3sN2Ya6GqOYiTwQ==";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "wrap-comment-1.0.1" = {
      name = "wrap-comment";
      packageName = "wrap-comment";
      version = "1.0.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/wrap-comment/-/wrap-comment-1.0.1.tgz";
        sha512 =
          "APccrMwl/ont0RHFTXNAQfM647duYYEfs6cngrIyTByTI0xbWnDnPSptFZhS68L4WCjt2ZxuhCFwuY6Pe88KZQ==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 =
          "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
  args = {
    name = "maison-frontend";
    packageName = "maison-frontend";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      (sources."@goto-bus-stop/common-shake-2.3.0" // {
        dependencies = [ sources."acorn-5.7.3" ];
      })
      sources."JSONStream-1.3.5"
      sources."acorn-6.2.1"
      sources."acorn-dynamic-import-4.0.0"
      sources."acorn-node-1.7.0"
      sources."acorn-walk-6.2.0"
      sources."amdefine-1.0.1"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."array-from-2.1.1"
      sources."asn1.js-4.10.1"
      (sources."assert-1.5.0" // {
        dependencies = [ sources."inherits-2.0.1" sources."util-0.10.3" ];
      })
      sources."balanced-match-1.0.0"
      sources."base64-js-1.3.1"
      sources."bn.js-4.11.8"
      sources."brace-expansion-1.1.11"
      sources."brorand-1.1.0"
      (sources."browser-pack-5.0.1" // {
        dependencies = [
          sources."combine-source-map-0.6.1"
          sources."convert-source-map-1.1.3"
          sources."inline-source-map-0.5.0"
          sources."isarray-0.0.1"
          sources."readable-stream-1.1.14"
          sources."source-map-0.4.4"
          sources."string_decoder-0.10.31"
          sources."through2-1.1.1"
        ];
      })
      sources."browser-pack-flat-3.4.2"
      sources."browser-process-hrtime-0.1.3"
      (sources."browser-resolve-1.11.3" // {
        dependencies = [ sources."resolve-1.1.7" ];
      })
      sources."browser-unpack-1.4.2"
      (sources."browserify-16.5.0" // {
        dependencies = [ sources."browser-pack-6.1.0" ];
      })
      sources."browserify-aes-1.2.0"
      sources."browserify-cipher-1.0.1"
      sources."browserify-des-1.0.2"
      sources."browserify-rsa-4.0.1"
      sources."browserify-sign-4.0.4"
      sources."browserify-zlib-0.2.0"
      sources."buffer-5.4.3"
      sources."buffer-from-1.1.1"
      sources."buffer-xor-1.0.3"
      sources."builtin-status-codes-3.0.0"
      sources."bundle-collapser-1.3.0"
      sources."cached-path-relative-1.0.2"
      sources."call-matcher-1.1.0"
      sources."camel-case-3.0.0"
      sources."chalk-1.1.3"
      sources."choo-7.0.0"
      sources."cipher-base-1.0.4"
      (sources."combine-source-map-0.8.0" // {
        dependencies = [ sources."convert-source-map-1.1.3" ];
      })
      sources."commander-2.20.0"
      sources."common-shakeify-0.6.2"
      sources."concat-map-0.0.1"
      sources."concat-stream-1.6.2"
      sources."console-browserify-1.2.0"
      sources."constants-browserify-1.0.0"
      sources."convert-source-map-1.6.0"
      sources."core-js-2.6.9"
      sources."core-util-is-1.0.2"
      sources."count-lines-0.1.2"
      sources."create-ecdh-4.0.3"
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."crypto-browserify-3.12.0"
      sources."d-1.0.1"
      sources."dash-ast-1.0.0"
      sources."debug-3.2.6"
      sources."dedent-0.7.0"
      sources."deep-equal-1.0.1"
      sources."deep-is-0.1.3"
      sources."defined-1.0.0"
      sources."deps-sort-2.0.1"
      sources."des.js-1.0.1"
      sources."detective-5.2.0"
      sources."diffie-hellman-5.0.3"
      sources."document-ready-2.0.2"
      sources."dom-walk-0.1.1"
      sources."domain-browser-1.2.0"
      sources."duplexer-0.1.1"
      sources."duplexer2-0.1.4"
      sources."duplexify-3.7.1"
      sources."elliptic-6.5.2"
      sources."end-of-stream-1.4.1"
      sources."envify-4.1.0"
      sources."es5-ext-0.10.50"
      sources."es6-iterator-2.0.3"
      sources."es6-map-0.1.5"
      sources."es6-set-0.1.5"
      sources."es6-symbol-3.1.1"
      sources."es6-weak-map-2.0.3"
      sources."escape-string-regexp-1.0.5"
      (sources."escodegen-1.11.1" // {
        dependencies = [ sources."esprima-3.1.3" sources."source-map-0.6.1" ];
      })
      sources."escope-3.6.0"
      sources."esprima-4.0.1"
      sources."espurify-1.8.1"
      sources."esrecurse-4.2.1"
      sources."estraverse-4.2.0"
      sources."estree-is-function-1.0.0"
      sources."estree-is-identifier-1.0.0"
      sources."estree-is-member-expression-1.0.0"
      sources."estree-is-require-1.0.0"
      sources."esutils-2.0.3"
      sources."event-emitter-0.3.5"
      sources."events-2.1.0"
      sources."evp_bytestokey-1.0.3"
      sources."extend-1.3.0"
      (sources."falafel-2.1.0" // {
        dependencies = [ sources."acorn-5.7.3" sources."isarray-0.0.1" ];
      })
      sources."fast-levenshtein-2.0.6"
      sources."fast-safe-stringify-2.0.7"
      sources."foreach-2.0.5"
      sources."from2-2.3.0"
      sources."from2-string-1.1.0"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."get-assigned-identifiers-1.2.0"
      sources."glob-7.1.6"
      sources."global-4.4.0"
      sources."has-1.0.3"
      sources."has-ansi-2.0.0"
      sources."hash-base-3.0.4"
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      sources."htmlescape-1.1.1"
      sources."https-browserify-1.0.0"
      sources."hyperscript-attribute-to-property-1.0.2"
      sources."hyperx-2.5.4"
      sources."ieee754-1.1.13"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."inline-source-map-0.6.2"
      (sources."insert-module-globals-7.2.0" // {
        dependencies = [ sources."is-buffer-1.1.6" ];
      })
      sources."is-boolean-attribute-0.0.1"
      sources."is-buffer-2.0.3"
      sources."isarray-1.0.0"
      sources."json-stable-stringify-0.0.1"
      sources."jsonify-0.0.0"
      sources."jsonparse-1.3.1"
      sources."labeled-stream-splicer-2.0.2"
      sources."levn-0.3.0"
      sources."lodash.memoize-3.0.4"
      sources."lower-case-1.1.4"
      sources."magic-string-0.23.2"
      sources."md5.js-1.3.5"
      sources."merge-source-map-1.0.4"
      sources."miller-rabin-4.0.1"
      sources."min-document-2.19.0"
      sources."minify-stream-1.2.0"
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [ sources."minimist-0.0.8" ];
      })
      sources."module-deps-6.2.2"
      sources."ms-2.1.2"
      (sources."multi-stage-sourcemap-0.2.1" // {
        dependencies = [ sources."source-map-0.1.43" ];
      })
      sources."mutexify-1.2.0"
      sources."nanoassert-1.1.0"
      sources."nanobench-2.1.1"
      sources."nanobus-4.4.0"
      sources."nanocomponent-6.5.2"
      sources."nanohref-3.1.0"
      sources."nanohtml-1.6.3"
      sources."nanolru-1.0.0"
      sources."nanomorph-5.4.0"
      sources."nanoquery-1.3.0"
      sources."nanoraf-3.1.0"
      sources."nanorouter-4.0.0"
      sources."nanoscheduler-1.0.3"
      sources."nanotiming-7.3.1"
      sources."next-tick-1.0.0"
      sources."no-case-2.3.2"
      sources."normalize-html-whitespace-0.2.0"
      sources."object-assign-4.1.1"
      sources."object-keys-1.1.1"
      sources."on-load-3.4.1"
      sources."once-1.4.0"
      sources."optionator-0.8.2"
      sources."os-browserify-0.3.0"
      sources."pako-1.0.11"
      sources."parents-1.0.1"
      sources."parse-asn1-5.1.5"
      sources."path-browserify-0.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."path-platform-0.11.15"
      sources."pbkdf2-3.0.17"
      sources."prelude-ls-1.1.2"
      sources."pretty-hrtime-1.0.3"
      sources."process-0.11.10"
      sources."process-nextick-args-2.0.1"
      sources."public-encrypt-4.0.3"
      sources."punycode-1.4.1"
      sources."querystring-0.2.0"
      sources."querystring-es3-0.2.1"
      sources."randombytes-2.1.0"
      sources."randomfill-1.0.4"
      sources."read-only-stream-2.0.0"
      sources."readable-stream-2.3.6"
      sources."remove-array-items-1.1.1"
      sources."resolve-1.15.1"
      sources."ripemd160-2.0.2"
      sources."safe-buffer-5.1.2"
      sources."scope-analyzer-2.0.5"
      sources."scroll-to-anchor-1.1.0"
      sources."sha.js-2.4.11"
      sources."shasum-1.0.2"
      sources."shasum-object-1.0.0"
      sources."shell-quote-1.7.2"
      sources."simple-concat-1.0.0"
      sources."source-map-0.5.7"
      (sources."source-map-support-0.5.13" // {
        dependencies = [ sources."source-map-0.6.1" ];
      })
      sources."sourcemap-codec-1.4.6"
      sources."stream-browserify-2.0.2"
      sources."stream-combiner-0.2.2"
      sources."stream-combiner2-1.1.1"
      (sources."stream-http-3.1.0" // {
        dependencies = [ sources."readable-stream-3.6.0" ];
      })
      sources."stream-shift-1.0.0"
      sources."stream-splicer-2.0.1"
      sources."string_decoder-1.1.1"
      sources."strip-ansi-3.0.1"
      sources."subarg-1.0.0"
      sources."supports-color-2.0.0"
      sources."syntax-error-1.4.0"
      (sources."terser-3.17.0" // {
        dependencies = [ sources."source-map-0.6.1" ];
      })
      sources."through-2.3.8"
      sources."through2-2.0.5"
      sources."timers-browserify-1.4.2"
      sources."tinyify-2.5.1"
      sources."transform-ast-2.4.4"
      sources."tty-browserify-0.0.1"
      sources."type-1.0.3"
      sources."type-check-0.3.2"
      sources."typedarray-0.0.6"
      (sources."uglifyify-5.0.1" // {
        dependencies = [ sources."convert-source-map-1.1.3" ];
      })
      sources."umd-3.0.3"
      (sources."unassert-1.5.1" // {
        dependencies = [ sources."acorn-4.0.13" ];
      })
      (sources."unassertify-2.1.1" // {
        dependencies = [ sources."acorn-5.7.3" ];
      })
      sources."undeclared-identifiers-1.1.3"
      sources."upper-case-1.1.3"
      (sources."url-0.11.0" // { dependencies = [ sources."punycode-1.3.2" ]; })
      (sources."util-0.10.4" // {
        dependencies = [ sources."inherits-2.0.3" ];
      })
      sources."util-deprecate-1.0.2"
      sources."vm-browserify-1.1.2"
      sources."wayfarer-7.0.0"
      sources."wordwrap-1.0.0"
      sources."wrap-comment-1.0.1"
      sources."wrappy-1.0.2"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The frontend code for maison";
      license = "0BSD";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in {
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
